import type { Metadata } from "next";
import localFont from "next/font/local";
import { Afacad } from 'next/font/google';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const afacad = Afacad({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-afacad',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${afacad.variable} font-afacad antialiased bg-slate-500`}
      >
        {children}
      </body>
    </html>
  );
}
